name: Build & push Docker image

on: push
  #push
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out src
      uses: actions/checkout@v4
      
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: public/shvedov/pocketbase
        #tags: v1, latest
        addLatest: true
        registry: jfrog.it-academy.by
        dockerfile: app/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}