name: Build & push Docker image

on: push
  #push
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push
      id: gen_tags
      run: echo 'GITHUB_REF_NAME='$GITHUB_REF_NAME
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: public/shvedov/pocketbase
        #tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
        tags: ${{ github.ref_name }}
        #tags: v1, latest
        #addLatest: true
        registry: jfrog.it-academy.by
        dockerfile: app/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}